//USER TYPES
export const AUTH_USER_REQUEST = "AUTH_USER_REQUEST"
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS"
export const AUTH_USER_FAIL = "AUTH_USER_FAIL"
export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL"

//FLEET TYPES
export const GET_ALL_FLEETS_REQUEST = "GET_ALL_FLEETS_REQUEST"
export const GET_ALL_FLEETS_SUCCESS = "GET_ALL_FLEETS_SUCCESS"
export const GET_ALL_FLEETS_FAIL = "GET_ALL_FLEETS_FAIL"
export const SEARCH_FLEET_REQUEST = "SEARCH_FLEET_REQUEST"
export const SEARCH_FLEET_SUCCESS = "SEARCH_FLEET_SUCCESS"
export const SEARCH_FLEET_FAIL = "SEARCH_FLEET_FAIL"

//UI TYPES
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"